# ViEWS-ESCWA model respecified in VIEWS 3 form
-- without the Retrain and Retrieve wrapper

In [5]:
# Basics
import numpy as np
import pandas as pd
# Views 3
import views_runs
from viewser.operations import fetch
#from views_forecasts.extensions import *
from viewser import Queryset, Column

In [6]:
! pwd

/Users/sarakallis/Documents/PRIO Local/views_pipeline/models/electric_relaxation/notebooks

# turn into: src/dataloaders/get_forecasting_data.py

In [7]:
qs_cm_cflong  = (Queryset("escwa001_cflong", "country_month")
                # target variable
                .with_column(Column("ged_sb_dep", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            )
                # timelag 0 of target variable
                .with_column(Column("ged_sb_dummy_t0", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            )
                # further timelags of target variable
                # sb
                .with_column(Column("ged_sb_dummy_t1", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_sb_dummy_t2", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(2)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_sb_dummy_t3", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            ) 
                .with_column(Column("ged_sb_dummy_t3", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )  
                .with_column(Column("ged_sb_dummy_t4", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(4)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_sb_dummy_t5", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(5)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_sb_dummy_t6", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(6)
                            .transform.missing.fill()
                            )
                        
                # os
                .with_column(Column("ged_os_dummy_t0", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_os_dummy_t1", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_os_dummy_t2", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(2)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_os_dummy_t3", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_os_dummy_t3", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )                     
                .with_column(Column("ged_os_dummy_t4", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(4)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_os_dummy_t5", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(5)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_os_dummy_t6", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(6)
                            .transform.missing.fill()
                            )
                # ns
                .with_column(Column("ged_ns_dummy_t0", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_ns_dummy_t1", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_ns_dummy_t2", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(2)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_ns_dummy_t3", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_ns_dummy_t3", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(1)
                            .transform.missing.fill()
                            )  
                .with_column(Column("ged_ns_dummy_t4", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(4)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_ns_dummy_t5", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(5)
                            .transform.missing.fill()
                            )
                .with_column(Column("ged_ns_dummy_t6", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.bool.gte(25)
                            .transform.missing.fill()
                            .transform.temporal.tlag(6)
                            .transform.missing.fill()
                            )
                # Decay functions
                # sb
                .with_column(Column("decay_ged_sb_1", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(1)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_sb_5", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(5)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_sb_25", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(25)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_sb_100", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(100)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_sb_500", from_table="ged2_cm", from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(500)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                # os
                
                .with_column(Column("decay_ged_os_1", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(1)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_os_5", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(5)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_os_25", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(25)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_os_100", from_table="ged2_cm", from_column="ged_os_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(100)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )         
                        
                # ns
                .with_column(Column("decay_ged_ns_1", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(1)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_ns_5", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(5)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_ns_25", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(25)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("decay_ged_ns_100", from_table="ged2_cm", from_column="ged_ns_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(100)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.missing.replace_na()
                            )
                        
                # Spatial lag decay functions
                        # sb
                .with_column(Column("splag_1_decay_ged_sb_25", from_table="ged2_cm",
                                    from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(25)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.spatial.countrylag(1, 1, 0, 0)
                            .transform.missing.replace_na()
                            )

                .with_column(Column("splag_1_decay_ged_sb_500", from_table="ged2_cm",
                                    from_column="ged_sb_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(500)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.spatial.countrylag(1, 1, 0, 0)
                            .transform.missing.replace_na()
                            )
                # os
                .with_column(Column("splag_1_decay_ged_os_25", from_table="ged2_cm",
                                    from_column="ged_os_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(25)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.spatial.countrylag(1, 1, 0, 0)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("splag_1_decay_ged_os_500", from_table="ged2_cm",
                                    from_column="ged_os_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(500)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.spatial.countrylag(1, 1, 0, 0)
                            .transform.missing.replace_na()
                            )
                # ns
                .with_column(Column("splag_1_decay_ged_ns_25", from_table="ged2_cm",
                                    from_column="ged_ns_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(25)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.spatial.countrylag(1, 1, 0, 0)
                            .transform.missing.replace_na()
                            )
                .with_column(Column("splag_1_decay_ged_ns_500", from_table="ged2_cm",
                                    from_column="ged_ns_best_sum_nokgi")
                            .transform.missing.replace_na()
                            .transform.bool.gte(500)
                            .transform.temporal.time_since()
                            .transform.temporal.decay(24)
                            .transform.spatial.countrylag(1, 1, 0, 0)
                            .transform.missing.replace_na()
                            )
            
                .with_theme("views-escwa")
                .describe("""Views-escwa conflict history, cm level


                            """)
                )

#data = qs_cm_cflong.publish().fetch()
data = qs_cm_cflong.fetch()
# Recast all columns to float because of an excessive assert in the stepshift library
data = data.astype(float)
data.head()

 .

                     ged_sb_dep  ged_sb_dummy_t0  ged_os_dummy_t0  \
month_id country_id
1        1                  0.0              0.0              0.0
         2                  0.0              0.0              0.0
         3                  0.0              0.0              0.0
         4                  0.0              0.0              0.0
         5                  0.0              0.0              0.0

                     ged_ns_dummy_t0  ged_sb_dummy_t1  ged_sb_dummy_t2  \
month_id country_id
1        1                       0.0              0.0              0.0
         2                       0.0              0.0              0.0
         3                       0.0              0.0              0.0
         4                       0.0              0.0              0.0
         5                       0.0              0.0              0.0

                     ged_sb_dummy_t3  _ged_sb_dummy_t3  ged_sb_dummy_t4  \
month_id country_id
1        1                       0.0               0.0              0.0
         2                       0.0               0.0              0.0
         3                       0.0               0.0              0.0
         4                       0.0               0.0              0.0
         5                       0.0               0.0              0.0

                     ged_sb_dummy_t5  ...  decay_ged_ns_1  decay_ged_ns_5  \
month_id country_id                   ...
1        1                       0.0  ...             0.0             0.0
         2                       0.0  ...             0.0             0.0
         3                       0.0  ...             0.0             0.0
         4                       0.0  ...             0.0             0.0
         5                       0.0  ...             0.0             0.0

                     decay_ged_ns_25  decay_ged_ns_100  \
month_id country_id
1        1                       0.0               0.0
         2                       0.0               0.0
         3                       0.0               0.0
         4                       0.0               0.0
         5                       0.0               0.0

                     splag_1_decay_ged_sb_25  splag_1_decay_ged_sb_500  \
month_id country_id
1        1                               0.0                       0.0
         2                               0.0                       0.0
         3                               0.0                       0.0
         4                               0.0                       0.0
         5                               0.0                       0.0

                     splag_1_decay_ged_os_25  splag_1_decay_ged_os_500  \
month_id country_id
1        1                               0.0                       0.0
         2                               0.0                       0.0
         3                               0.0                       0.0
         4                               0.0                       0.0
         5                               0.0                       0.0

                     splag_1_decay_ged_ns_25  splag_1_decay_ged_ns_500
month_id country_id
1        1                               0.0                       0.0
         2                               0.0                       0.0
         3                               0.0                       0.0
         4                               0.0                       0.0
         5                               0.0                       0.0

[5 rows x 44 columns]

# configs/config_common or configs/config_partitioner

In [8]:

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from stepshift.views import StepshiftedModels
# Parameters for the model  
steps = [*range(1, 36+1, 1)] # Which steps to train and predict for
#steps = [1,3,6] # Shortened set of steps for the impatient
target = 'ged_sb_dep'

calib_partitioner_dict = {"train":(121,396),"predict":(409,456)}
test_partitioner_dict = {"train":(121,456),"predict":(457,504)}
future_partitioner_dict = {"train":(121,504),"predict":(529,529)}

# src/training/train_forecasting_model.py

In [9]:
calib_partition = views_runs.DataPartitioner({'calib':calib_partitioner_dict}) #stepshifter implementation (views_runs is a class)
future_partition = views_runs.DataPartitioner({'future':future_partitioner_dict}) #stepshifter implementation 

# Fitting model
base_model = RandomForestClassifier(n_estimators=100, n_jobs=-2)
stepshifter_def = StepshiftedModels(base_model,steps,target)

# Fitting for calibration run, calibration partition
stepshifter_model_calib = views_runs.ViewsRun(calib_partition,stepshifter_def)
stepshifter_model_calib.fit('calib','train',data)

# Fitting for future run, future partition
stepshifter_model_future = views_runs.ViewsRun(future_partition,stepshifter_def)
stepshifter_model_future.fit('future','train',data)

# src/forecasting/generate_forecast.py

In [11]:
# Predictions for test partition:
calib_predictions = stepshifter_model_calib.predict('calib','predict',data, proba=True)

In [12]:
calib_predictions.head()

                     ged_sb_dep  ged_sb_dummy_t0  ged_os_dummy_t0  \
month_id country_id
409      1                  0.0              0.0              0.0
         2                  0.0              0.0              0.0
         3                  0.0              0.0              0.0
         4                  0.0              0.0              0.0
         5                  0.0              0.0              0.0

                     ged_ns_dummy_t0  ged_sb_dummy_t1  ged_sb_dummy_t2  \
month_id country_id
409      1                       0.0              0.0              0.0
         2                       0.0              0.0              0.0
         3                       0.0              0.0              0.0
         4                       0.0              0.0              0.0
         5                       0.0              0.0              0.0

                     ged_sb_dummy_t3  _ged_sb_dummy_t3  ged_sb_dummy_t4  \
month_id country_id
409      1                       0.0               0.0              0.0
         2                       0.0               0.0              0.0
         3                       0.0               0.0              0.0
         4                       0.0               0.0              0.0
         5                       0.0               0.0              0.0

                     ged_sb_dummy_t5  ...  step_pred_33  step_pred_34  \
month_id country_id                   ...
409      1                       0.0  ...           0.0           0.0
         2                       0.0  ...           0.0           0.0
         3                       0.0  ...           0.0           0.0
         4                       0.0  ...           0.0           0.0
         5                       0.0  ...           0.0           0.0

                     step_pred_35  step_pred_36  step_pred_4  step_pred_5  \
month_id country_id
409      1                    0.0           0.0          0.0          0.0
         2                    0.0           0.0          0.0          0.0
         3                    0.0           0.0          0.0          0.0
         4                    0.0           0.0          0.0          0.0
         5                    0.0           0.0          0.0          0.0

                     step_pred_6  step_pred_7  step_pred_8  step_pred_9
month_id country_id
409      1                   0.0          0.0          0.0          0.0
         2                   0.0          0.0          0.0          0.0
         3                   0.0          0.0          0.0          0.0
         4                   0.0          0.0          0.0          0.0
         5                   0.0          0.0          0.0          0.0

[5 rows x 80 columns]

In [13]:
calib_predictions.describe()

,ged_sb_dep,ged_sb_dummy_t0,ged_os_dummy_t0,ged_ns_dummy_t0,ged_sb_dummy_t1,ged_sb_dummy_t2,ged_sb_dummy_t3,_ged_sb_dummy_t3,ged_sb_dummy_t4,ged_sb_dummy_t5,...,step_pred_33,step_pred_34,step_pred_35,step_pred_36,step_pred_4,step_pred_5,step_pred_6,step_pred_7,step_pred_8,step_pred_9
count,9168.000000,9168.000000,9168.000000,9168.000000,9168.000000,9168.000000,9168.000000,9168.000000,9168.000000,9168.000000,...,9168.0,9168.0,9168.0,9168.0,9168.000000,9168.000000,9168.000000,9168.000000,9168.000000,9168.000000
mean,0.075153,0.075153,0.033050,0.036322,0.075044,0.074607,0.075044,0.075044,0.073953,0.073844,...,inf,inf,inf,inf,0.074770,0.074938,0.075011,0.074604,0.074736,0.074528
std,0.263652,0.263652,0.178776,0.187100,0.263476,0.262771,0.263476,0.263476,0.261708,0.261531,...,NaN,NaN,NaN,NaN,0.239002,0.239331,0.239643,0.239266,0.238990,0.238090
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,inf,inf,inf,inf,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [14]:
# Predictions for the future:
future_partition = views_runs.DataPartitioner({'future':future_partitioner_dict})
future_predictions = stepshifter_model_future.future_predict('future','predict',data)
# Predictions for the future, alternative method:
future_point_predictions = stepshifter_model_future.future_point_predict(time=529, data=data, proba=True)
future_point_predictions.tail(20)

feature              step_combined
month_id country_id
565      205              0.032541
         206              0.062064
         209              0.170000
         213              0.230000
         214              0.220000
         218              0.430000
         220              0.850000
         222              0.340000
         223              0.420000
         231              0.000000
         232              0.030000
         233              0.000000
         234              0.065739
         235              0.120000
         237              0.200000
         242              0.140000
         243              0.125042
         244              0.070720
         245              0.690000
         246              0.180000

In [15]:
future_point_predictions.describe()

feature  step_combined
count      6876.000000
mean          0.137513
std           0.191055
min           0.000000
25%           0.023425
50%           0.062464
75%           0.160492
max           0.970000

In [3]:
# Docstrings: 
views_runs?

Type:        module
String form: <module 'views_runs' from '/Applications/anaconda3/envs/viewser/lib/python3.9/site-packages/views_runs/__init__.py'>
File:        /Applications/anaconda3/envs/viewser/lib/python3.9/site-packages/views_runs/__init__.py
Docstring:
views_runs
==========

This package collects views related tools and utilities used when planning,
training and storing views "runs" of predictions.

classes:
    ViewsRun:
        Class that encapsulates StepshiftedModels and DataPartitioner objects
        to provide a nice API for training and producing predictions.
    Storage:
        A class that exposes the viewser model_storage storage driver, used to
        save and load trained model objects.
    StepshiftedModels:
        Model class from the stepshift package that lets you train stepshifted
        models.
    DataPartitioner:
        Utility class for subsetting data in time, that lets you define
        tranining and testing periods, as well as do operations to ensure no
        overlap exists between these periods.
    ModelMetadata:
        Class used to specify metadata for trained model objects.

modules:
    utilities: Various utility functions ported from views 2
    stats: Resampling functions
    run: Defines the ViewsRun class
    storage: Defines the Storage class
    validation: Functions used internally to validate data

Each class and module mentioned here has more documentation. Use the help()
function.

In [4]:
# Documentation:
help(views_runs)

Help on package views_runs:

NAME
    views_runs

DESCRIPTION
    views_runs
    ==========

    This package collects views related tools and utilities used when planning,
    training and storing views "runs" of predictions.

    classes:
        ViewsRun:
            Class that encapsulates StepshiftedModels and DataPartitioner objects
            to provide a nice API for training and producing predictions.
        Storage:
            A class that exposes the viewser model_storage storage driver, used to
            save and load trained model objects.
        StepshiftedModels:
            Model class from the stepshift package that lets you train stepshifted
            models.
        DataPartitioner:
            Utility class for subsetting data in time, that lets you define
            tranining and testing periods, as well as do operations to ensure no
            overlap exists between these periods.
        ModelMetadata:
            Class used to specify metadata for trained model objects.

    modules:
        utilities: Various utility functions ported from views 2
        stats: Resampling functions
        run: Defines the ViewsRun class
        storage: Defines the Storage class
        validation: Functions used internally to validate data

    Each class and module mentioned here has more documentation. Use the help()
    function.

PACKAGE CONTENTS
    operations
    run
    run_result
    stats
    storage
    utilities
    validation
    vendoring

FILE
    /Applications/anaconda3/envs/viewser/lib/python3.9/site-packages/views_runs/__init__.py

Add:
- Drift detection
- wandb
- Hyperparameter testing